# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install Terraform latest'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
  displayName: 'Terraform : azurerm'
  inputs:
    workingDirectory: configuration
    backendServiceArm: $(CHANGE_FOR_YOUR_AZURE_SUBSCRIPTION_SERVICE)
    backendAzureRmResourceGroupName: $(CHANGE_FOR_YOUR_AZURE_RESOURCE_GROUP_NAME)
    backendAzureRmStorageAccountName: $(CHANGE_FOR_YOUR_STORAGE_ACCOUNT_NAME)
    backendAzureRmContainerName: $(CHANGE_FOR_YOUR_STORAGE_CONTAINER_NAME)
    backendAzureRmKey: terraform.tfstate

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
  displayName: 'Terraform : azurerm'
  inputs:
    command: plan
    workingDirectory: configuration
    environmentServiceNameAzureRM: $(CHANGE_FOR_YOUR_SERVICE_CONNECTION_NAME)

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
  displayName: 'Terraform : azurerm'
  inputs:
    command: apply
    workingDirectory: $(CHANGE_FOR_YOUR_DIRECTORY_WHERE_TERRAFORM_SCRIPT_IS)
    commandOptions: '-auto-approve '
    environmentServiceNameAzureRM: $(CHANGE_FOR_YOUR_SERVICE_CONNECTION_NAME)
